---
- import_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- import_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Docker.
  package: name={{ docker_package }} state={{ docker_package_state }}

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: started
    enabled: yes

- import_tasks: docker-compose.yml
  when: docker_install_compose

- name: Installing deps package
  pip:
      name: docker-py
      version: 1.10.6

- name: Pulling base images
  docker_image:
      name: "{{ item }}"
  with_items: "{{ base_images }}"
